# This is a basic workflow to help you get started with Actions

name: Veracode Upload and Scan Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it and copies all sources into ZIP file for submitting for analysis. Replace this section with your applications build steps
      - uses: actions/checkout@v2
      - name: Zip Folder
        run: zip -r release.zip . -x ".git/*" ".github/*"

      - uses: actions/upload-artifact@master
        with:
          name: python-package
          path: release.zip

  # Veracode Upload And Scan
  veracode:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: python-package

      - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
        with: 
          java-version: '8'

      - uses: actions/download-artifact@v2 # Copy files from repository to docker container so the next uploadandscan action can access them.
        with:
          name: python-package

        # You may pin to the exact commit or the version.
        # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
      - uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # appname
          #appname: # default is ${{ github.repository }}
          # createprofile
          #createprofile: # default is true
          # filepath
          filepath: 'release.zip'
          # version
          #version: # default is Scan from Github job: ${{ github.run_id }}
          # vid
          vid: '${{ secrets.VERACODE_API_ID }}'
          # vkey
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          # true or false
          # createsandbox: # optional
          createsandbox: true
          # name of the sandbox
          #sandboxname: # optional
          sandboxname: 'Github-Actions'
          # wait X minutes for the scan to complete
          #scantimeout: # optional
          # modules to exclude from module selection
          #exclude: # optional
          # modules to include in module selection
          #include: # optional
          include: 'release.zip'
          # business criticality - policy selection
          #criticality: # optional
          criticality: 'High'
          # filename pattern
          #pattern: # optional
          # replacement
          #replacement: # optional
          # replacement
          #sandboxid: # optional
          # All top level modules
          #scanallnonfataltoplevelmodules: # optional
          # platform selected modules
          #selected: # optional
          # selected modules like from previous scan
          #selectedpreviously: # optional
          # teams
          #teams: # optional
          # teams
          #toplevel: # optional
