# This is a basic workflow to help you get started with Actions

name: Veracode Upload and Scan Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Easy Zip Files
        # You may pin to the exact commit or the version.
        # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
        uses: vimtor/action-zip@v1
        with:
          # Files or directories to zip
          files: python_sample_app/*.py
          # Name of output zip file
          # dest: # optional, default is result.zip
          # Whether to add subdirectories to simply zip all files to the root
          #recursive: # optional, default is true
      - name: Veracode Upload And Scan
        # You may pin to the exact commit or the version.
        # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # appname
          #appname: # default is ${{ github.repository }}
          # createprofile
          #createprofile: # default is true
          # filepath
          filepath: 'result.zip'
          # version
          #version: # default is Scan from Github job: ${{ github.run_id }}
          # vid
          vid: '${{ secrets.VERACODE_API_ID }}'
          # vkey
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          # true or false
          # createsandbox: # optional
          createsandbox: true
          # name of the sandbox
          #sandboxname: # optional
          sandboxname: 'Github-Actions'
          # wait X minutes for the scan to complete
          #scantimeout: # optional
          # modules to exclude from module selection
          #exclude: # optional
          # modules to include in module selection
          #include: # optional
          include: 'result.zip'
          # business criticality - policy selection
          #criticality: # optional
          criticality: 'High'
          # filename pattern
          #pattern: # optional
          # replacement
          #replacement: # optional
          # replacement
          #sandboxid: # optional
          # All top level modules
          #scanallnonfataltoplevelmodules: # optional
          # platform selected modules
          #selected: # optional
          # selected modules like from previous scan
          #selectedpreviously: # optional
          # teams
          #teams: # optional
          # teams
          #toplevel: # optional
